### ISSUE TITLE
[BUG] ATabs show "More" menu when tabs are still in view + menu is cut off

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#746] opened 2024-05-31 20:16 UTC
**Describe the bug**

The ATabs component adds a "More" dropdown menu as a new tab once the viewport becomes too narrow to fit all of the tabs. However, it looks like it's not actually removing the tabs from being visible when the "More" menu is displayed. 

**To Reproduce**

1. Go to the incident detail page in XDR
2. Make sure left nav in shell app is expanded
3. Drag the edge of your browser to keep getting smaller until you see the "More" menu appear as the last item in the tabs (browser about 1075px wide)
4. Click "More" to see what's in the menu
5. Observe that "Report" is in the menu, even though the Report tab is still visible (Does "More" even need to be used at this point since the tabs all still fit?)
6. Drag the browser to be even smaller so that the "More" menu drops to a new line (1000px wide) 
7. Open it to see that menu is cut off by left nav in shell app (perhaps changing or allowing us to change the menu positioning would help?)
8. Observe that "Worklog" and "Report" are not both menu options, even though both tabs are still visible

**Screenshots**

<img width="1025" alt="Screenshot 2024-05-31 at 3 14 18 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/15b79626-2ba7-42da-8413-b7368690feda">

<img width="981" alt="Screenshot 2024-05-31 at 3 14 33 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/9b4f9491-f1ee-409e-98e2-715f40b39eb5">

**Comment by rwharrisjr** [comment] 2024-06-03 12:16
@androche fyi

**Comment by rwharrisjr** [comment] 2024-06-03 15:21
This is somewhat a caused by the page container width changing with the tab content. Updates in magna 2.0 handle changes in size better.

Should mostly be resolved by https://github.com/advthreat/incident-manager/pull/2715. There's still a tiny margin of about 3 pixels where the More button will show and it'll be empty... but it's really hard to hit that case without trying for it

**Comment by lukaskral** [comment] 2024-06-04 14:09
This behaviour on incident manager might have been caused by the way how tabs are implemented on incident detail page. Previously we were using something like this:
```tsx
<ATabGroup>
  <Link to="..."><ATab>Worklog</ATab></Link>
</ATabGroup>
```

which is probably not supported for overflow by magna react. In [this PR](https://github.com/advthreat/incident-manager/pull/2746) I changed it so it uses `ATab` component as a direct child of `ATabGroup` which probably fixed the issue on our side

**Comment by rwharrisjr** [comment] 2024-06-04 14:13
@lukaskral https://github.com/advthreat/incident-manager/pull/2715 is very similar, except it passes the Link component as the ATab's component. That combined with https://github.com/cisco-sbg-ui/magna-react/pull/739 should get thing working as expected, without any special logic for navigation

**Comment by lukaskral** [comment] 2024-06-04 14:19
thanks @rwharrisjr , I'll remove that part form my PR so I don't cause conflicts

**Closed** 2024-10-18 19:45 UTC
Labels: bug
